// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // json: "username"
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // json: "password"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // json: "user_id"
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`     // json: "api_key"
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"` // json: "is_admin"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LoginResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type SetLimitsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rps                 int32                  `protobuf:"varint,2,opt,name=rps,proto3" json:"rps,omitempty"`
	MaxTokens           int64                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxTokensPerRequest int64                  `protobuf:"varint,4,opt,name=max_tokens_per_request,json=maxTokensPerRequest,proto3" json:"max_tokens_per_request,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetLimitsRequest) Reset() {
	*x = SetLimitsRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimitsRequest) ProtoMessage() {}

func (x *SetLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimitsRequest.ProtoReflect.Descriptor instead.
func (*SetLimitsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *SetLimitsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetLimitsRequest) GetRps() int32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *SetLimitsRequest) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SetLimitsRequest) GetMaxTokensPerRequest() int64 {
	if x != nil {
		return x.MaxTokensPerRequest
	}
	return 0
}

type SetLimitsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rps                 int32                  `protobuf:"varint,2,opt,name=rps,proto3" json:"rps,omitempty"`
	MaxTokens           int64                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxTokensPerRequest int64                  `protobuf:"varint,4,opt,name=max_tokens_per_request,json=maxTokensPerRequest,proto3" json:"max_tokens_per_request,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetLimitsResponse) Reset() {
	*x = SetLimitsResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimitsResponse) ProtoMessage() {}

func (x *SetLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimitsResponse.ProtoReflect.Descriptor instead.
func (*SetLimitsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *SetLimitsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetLimitsResponse) GetRps() int32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *SetLimitsResponse) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SetLimitsResponse) GetMaxTokensPerRequest() int64 {
	if x != nil {
		return x.MaxTokensPerRequest
	}
	return 0
}

type SuspendUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendUserRequest) Reset() {
	*x = SuspendUserRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendUserRequest) ProtoMessage() {}

func (x *SuspendUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendUserRequest.ProtoReflect.Descriptor instead.
func (*SuspendUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *SuspendUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SuspendUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendUserResponse) Reset() {
	*x = SuspendUserResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendUserResponse) ProtoMessage() {}

func (x *SuspendUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendUserResponse.ProtoReflect.Descriptor instead.
func (*SuspendUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *SuspendUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuspendUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Represents the LimitInfo struct returned by the limiter
type LimitInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens       int64                  `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`                       // Go json mapping: "MaxTokens"
	MaxTokensPerReq int64                  `protobuf:"varint,2,opt,name=max_tokens_per_req,json=maxTokensPerReq,proto3" json:"max_tokens_per_req,omitempty"` // Go json mapping: "MaxTokensPerReq"
	UsedTokens      int64                  `protobuf:"varint,3,opt,name=used_tokens,json=usedTokens,proto3" json:"used_tokens,omitempty"`                    // Go json mapping: "UsedTokens"
	Rps             float64                `protobuf:"fixed64,4,opt,name=rps,proto3" json:"rps,omitempty"`                                                   // Go json mapping: "RPS"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LimitInfo) Reset() {
	*x = LimitInfo{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitInfo) ProtoMessage() {}

func (x *LimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitInfo.ProtoReflect.Descriptor instead.
func (*LimitInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *LimitInfo) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LimitInfo) GetMaxTokensPerReq() int64 {
	if x != nil {
		return x.MaxTokensPerReq
	}
	return 0
}

func (x *LimitInfo) GetUsedTokens() int64 {
	if x != nil {
		return x.UsedTokens
	}
	return 0
}

func (x *LimitInfo) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

// GET /admin/limits returns a map of UserID -> LimitInfo
type AllLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limits        map[string]*LimitInfo  `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllLimitsResponse) Reset() {
	*x = AllLimitsResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLimitsResponse) ProtoMessage() {}

func (x *AllLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLimitsResponse.ProtoReflect.Descriptor instead.
func (*AllLimitsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *AllLimitsResponse) GetLimits() map[string]*LimitInfo {
	if x != nil {
		return x.Limits
	}
	return nil
}

// Represents the ModelUsage struct
type ModelUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelUsage) Reset() {
	*x = ModelUsage{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUsage) ProtoMessage() {}

func (x *ModelUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUsage.ProtoReflect.Descriptor instead.
func (*ModelUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ModelUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ModelUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// GET /v1/usage returns a map of ModelName -> ModelUsage
type UsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsageByModel  map[string]*ModelUsage `protobuf:"bytes,1,rep,name=usage_by_model,json=usageByModel,proto3" json:"usage_by_model,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *UsageResponse) GetUsageByModel() map[string]*ModelUsage {
	if x != nil {
		return x.UsageByModel
	}
	return nil
}

// GET /admin/usage returns a map of UserID -> (ModelName -> ModelUsage)
type AllUsageResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UsageByUser   map[string]*UsageResponse `protobuf:"bytes,1,rep,name=usage_by_user,json=usageByUser,proto3" json:"usage_by_user,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllUsageResponse) Reset() {
	*x = AllUsageResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUsageResponse) ProtoMessage() {}

func (x *AllUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUsageResponse.ProtoReflect.Descriptor instead.
func (*AllUsageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *AllUsageResponse) GetUsageByUser() map[string]*UsageResponse {
	if x != nil {
		return x.UsageByUser
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Stream        bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\bproxy.v1\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\\\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"\x91\x01\n" +
	"\x10SetLimitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03rps\x18\x02 \x01(\x05R\x03rps\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x03R\tmaxTokens\x123\n" +
	"\x16max_tokens_per_request\x18\x04 \x01(\x03R\x13maxTokensPerRequest\"\x92\x01\n" +
	"\x11SetLimitsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03rps\x18\x02 \x01(\x05R\x03rps\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x03R\tmaxTokens\x123\n" +
	"\x16max_tokens_per_request\x18\x04 \x01(\x03R\x13maxTokensPerRequest\"-\n" +
	"\x12SuspendUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x13SuspendUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x8a\x01\n" +
	"\tLimitInfo\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x03R\tmaxTokens\x12+\n" +
	"\x12max_tokens_per_req\x18\x02 \x01(\x03R\x0fmaxTokensPerReq\x12\x1f\n" +
	"\vused_tokens\x18\x03 \x01(\x03R\n" +
	"usedTokens\x12\x10\n" +
	"\x03rps\x18\x04 \x01(\x01R\x03rps\"\xa4\x01\n" +
	"\x11AllLimitsResponse\x12?\n" +
	"\x06limits\x18\x01 \x03(\v2'.proxy.v1.AllLimitsResponse.LimitsEntryR\x06limits\x1aN\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proxy.v1.LimitInfoR\x05value:\x028\x01\"^\n" +
	"\n" +
	"ModelUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\"\xb7\x01\n" +
	"\rUsageResponse\x12O\n" +
	"\x0eusage_by_model\x18\x01 \x03(\v2).proxy.v1.UsageResponse.UsageByModelEntryR\fusageByModel\x1aU\n" +
	"\x11UsageByModelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.proxy.v1.ModelUsageR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x10AllUsageResponse\x12O\n" +
	"\rusage_by_user\x18\x01 \x03(\v2+.proxy.v1.AllUsageResponse.UsageByUserEntryR\vusageByUser\x1aW\n" +
	"\x10UsageByUserEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.proxy.v1.UsageResponseR\x05value:\x028\x01\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x97\x01\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x121\n" +
	"\bmessages\x18\x02 \x03(\v2\x15.proxy.v1.ChatMessageR\bmessages\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokensB\aZ\x05lb/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: proxy.v1.LoginRequest
	(*LoginResponse)(nil),         // 1: proxy.v1.LoginResponse
	(*SetLimitsRequest)(nil),      // 2: proxy.v1.SetLimitsRequest
	(*SetLimitsResponse)(nil),     // 3: proxy.v1.SetLimitsResponse
	(*SuspendUserRequest)(nil),    // 4: proxy.v1.SuspendUserRequest
	(*SuspendUserResponse)(nil),   // 5: proxy.v1.SuspendUserResponse
	(*LimitInfo)(nil),             // 6: proxy.v1.LimitInfo
	(*AllLimitsResponse)(nil),     // 7: proxy.v1.AllLimitsResponse
	(*ModelUsage)(nil),            // 8: proxy.v1.ModelUsage
	(*UsageResponse)(nil),         // 9: proxy.v1.UsageResponse
	(*AllUsageResponse)(nil),      // 10: proxy.v1.AllUsageResponse
	(*ChatMessage)(nil),           // 11: proxy.v1.ChatMessage
	(*ChatCompletionRequest)(nil), // 12: proxy.v1.ChatCompletionRequest
	nil,                           // 13: proxy.v1.AllLimitsResponse.LimitsEntry
	nil,                           // 14: proxy.v1.UsageResponse.UsageByModelEntry
	nil,                           // 15: proxy.v1.AllUsageResponse.UsageByUserEntry
}
var file_api_proto_depIdxs = []int32{
	13, // 0: proxy.v1.AllLimitsResponse.limits:type_name -> proxy.v1.AllLimitsResponse.LimitsEntry
	14, // 1: proxy.v1.UsageResponse.usage_by_model:type_name -> proxy.v1.UsageResponse.UsageByModelEntry
	15, // 2: proxy.v1.AllUsageResponse.usage_by_user:type_name -> proxy.v1.AllUsageResponse.UsageByUserEntry
	11, // 3: proxy.v1.ChatCompletionRequest.messages:type_name -> proxy.v1.ChatMessage
	6,  // 4: proxy.v1.AllLimitsResponse.LimitsEntry.value:type_name -> proxy.v1.LimitInfo
	8,  // 5: proxy.v1.UsageResponse.UsageByModelEntry.value:type_name -> proxy.v1.ModelUsage
	9,  // 6: proxy.v1.AllUsageResponse.UsageByUserEntry.value:type_name -> proxy.v1.UsageResponse
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
